### ISSUE TITLE
This dont work

### ISSUE THREAD

**Issue by Elercia** [404PlayaNotFound/templateJee#1]
How am I suppose to do ? gime some info plzzzzzz

Do you need the hour ? http://quelleheureestilenjoy.com/
http://quelleheureestilenjoy.com/
http://quelleheureestilenjoy.com/
http://quelleheureestilenjoy.com/
http://quelleheureestilenjoy.com/
http://quelleheureestilenjoy.com/

**Comment by T0mat1** [comment]
A watch is a timepiece intended to be carried or worn by a person. It is designed to keep working despite the motions caused by the person's activities. A wristwatch is designed to be worn around the wrist, attached by a watch strap or other type of bracelet. A pocket watch is designed for a person to carry in a pocket. The study of timekeeping is known as horology.

Watches progressed in the 17th century from spring-powered clocks, which appeared as early as the 14th century. During most of its history the watch was a mechanical device, driven by clockwork, powered by winding a mainspring, and keeping time with an oscillating balance wheel. These are called mechanical watches.[1][2] In the 1960s the electronic quartz watch was invented, which was powered by a battery and kept time with a vibrating quartz crystal. By the 1980s the quartz watch had taken over most of the market from the mechanical watch. Historically, this is called the quartz revolution.[3][4] Developments in the 2010s include smartwatches, which are elaborate computer-like electronic devices designed to be worn on a wrist. They generally incorporate timekeeping functions, but these are only a small subset of the smartwatch's facilities.

In general, modern watches often display the day, date, month and year. For mechanical watches, various extra features called "complications", such as moon-phase displays and the different types of tourbillon, are sometimes included.[5] Most electronic quartz watches, on the other hand, include time-related features such as timers, chronographs and alarm functions. Furthermore, some modern smartwatches even incorporate calculators, GPS[6] and Bluetooth technology or have heart-rate monitoring capabilities, and some of them use radio clock technology to regularly correct the time.

Today, most watches in the market that are inexpensive and medium-priced, used mainly for timekeeping, have quartz movements. However, expensive collectible watches, valued more for their elaborate craftsmanship, aesthetic appeal and glamorous design than for simple timekeeping, often have traditional mechanical movements, even though they are less accurate and more expensive than electronic ones.[3][4][7] As of 2018, the most expensive watch ever sold at auction is the Patek Philippe Henry Graves Supercomplication, which is the world's most complicated mechanical watch until 1989, fetching 24 million US dollars (23,237,000 CHF) in Geneva on November 11, 2014
